// YouTube writes this badge itself on fresh recommendations, and the wording is its own, not a
// translation of "New": Portuguese says "Novidade" but European Portuguese says "Novo", Japanese
// "新着", Traditional Chinese "新片". So the table holds YouTube's strings, read out of its own
// localized responses one locale at a time, rather than anything invented here. A locale the table
// does not name falls back to its base language, then to English.

const NEW_BADGE_TEXT_BY_LOCALE: Record<string, string> = {
  af: "Nuut",
  am: "አዲስ",
  ar: "جديد",
  as: "নতুন",
  az: "Yeni",
  be: "Новае",
  bg: "Ново",
  bn: "নতুন",
  bs: "Novo",
  ca: "Novetat",
  cs: "Nové",
  da: "Ny",
  de: "Neu",
  el: "Νέο",
  en: "New",
  "en-GB": "New",
  "en-IN": "New",
  es: "Nuevo",
  "es-419": "Nuevo",
  "es-US": "Nuevo",
  et: "Uus",
  eu: "Berria",
  fa: "جدید",
  fi: "Uusi",
  fil: "Bago",
  fr: "Nouveauté",
  "fr-CA": "Nouveauté",
  gl: "Novidade",
  gu: "નવો",
  he: "חדש",
  hi: "नया वीडियो",
  hr: "Novo",
  hu: "Új",
  hy: "Նոր",
  id: "Baru",
  is: "Nýtt",
  it: "Novità",
  iw: "חדש",
  ja: "新着",
  ka: "ახალი",
  kk: "Жаңа",
  km: "ថ្មី",
  kn: "ಹೊಸತು",
  ko: "신규",
  ky: "Жаңы",
  lo: "ໃໝ່",
  lt: "Naujas",
  lv: "Jaunums",
  mk: "Ново",
  ml: "പുതിയത്",
  mn: "Шинэ",
  mr: "नवीन",
  ms: "Baharu",
  my: "အသစ်",
  ne: "नयाँ",
  nl: "Nieuw",
  no: "Ny",
  or: "ନୂଆ",
  pa: "ਨਵਾਂ",
  pl: "Nowość",
  pt: "Novidade",
  "pt-PT": "Novo",
  ro: "Nou",
  ru: "Новинка",
  si: "නව",
  sk: "Nové",
  sl: "Novo",
  sq: "E re",
  sr: "Ново",
  "sr-Latn": "Novo",
  sv: "Ny",
  sw: "Mpya",
  ta: "புதிது",
  te: "కొత్తది",
  th: "ใหม่",
  tr: "Yeni",
  uk: "Нове",
  ur: "نیا",
  uz: "Yangi",
  vi: "Mới",
  "zh-CN": "新",
  "zh-HK": "全新",
  "zh-TW": "新片",
  zu: "Okusha"
};

const NEW_BADGE_TEXT_FALLBACK = "New";

export function newBadgeText() {
  const locale = ytcfg?.get("HL") || document.documentElement.lang;
  const [language] = locale.split("-");
  return NEW_BADGE_TEXT_BY_LOCALE[locale] ?? NEW_BADGE_TEXT_BY_LOCALE[language] ?? NEW_BADGE_TEXT_FALLBACK;
}
